name: test project 
on: push
jobs:
  test: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18 
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  deploy: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18 
      - name: install dependencies
        run: npm ci
      - name: Built project 
        run: npm run build
      - name: Deploy 
        run: eacho "deply..."